Repository JoelMichaelRutter/team-1-apr-hackathon-earth-day, pull requests merged in 2022-04, with the labels that each got.

#25 add home screen hero image in home app and styling
  earrrth/urls.py
  home/templates/home/index.html
  media/home-hero-optimised.jpg
  static/css/style.css
Labels: must have

#43 Contributions app
  .gitignore
  contributions/admin.py
  contributions/contexts.py
  contributions/forms.py
  contributions/migrations/0001_initial.py
  contributions/migrations/0002_reduce_reuse.py
  contributions/migrations/0003_auto_20220423_0843.py
  contributions/migrations/0004_auto_20220423_0944.py
  contributions/migrations/0005_auto_20220423_1010.py
  contributions/models.py
  contributions/static/contributions/js/contributions.js
  contributions/templates/contributions/contributions.html
  contributions/urls.py
  contributions/views.py
  earrrth/settings.py
  home/templates/home/index.html
  home/views.py
  profiles/apps.py
  profiles/migrations/0001_initial.py
  profiles/models.py
  profiles/signals.py
  requirements.txt
  static/css/style.css
  templates/base.html
Labels: must have

#50 Joel wire up app
  contributions/contexts.py
  contributions/migrations/0001_initial.py
  contributions/migrations/0002_reduce_reuse.py
  contributions/migrations/0003_auto_20220423_0843.py
  contributions/migrations/0004_auto_20220423_0944.py
  contributions/migrations/0005_auto_20220423_1010.py
  contributions/models.py
  contributions/urls.py
  home/templates/home/index.html
  profiles/migrations/0001_initial.py
  static/css/style.css
  templates/base.html
Labels: must have

#44 styling tabs on contributions page in new branch
  contributions/templates/contributions/contributions.html
  earrrth/settings.py
  static/css/style.css
Labels: must have

#52 fixed Attributed Error - context data no longer returned as list
  contributions/contexts.py
Labels: bug

#54 John t setup cloudinary
  contributions/templates/contributions/contributions.html
  earrrth/settings.py
  media/images/earth_solid.png
  profiles/admin.py
  profiles/migrations/0002_profileimage.py
  profiles/migrations/0003_alter_profileimage_owner.py
  profiles/migrations/0004_auto_20220423_2335.py
  profiles/migrations/0005_alter_userprofile_image.py
  profiles/migrations/0006_alter_userprofile_image.py
  profiles/models.py
  profiles/templates/profiles/profile.html
  profiles/views.py
Labels: must have

#59 Designed stat grids for home page
  home/templates/home/index.html
  static/css/style.css
Labels: must have

#63 Added wireframes and some minor changes to contrib context and index
  contributions/contexts.py
  contributions/migrations/0001_initial.py
  docs/wireframes/desktop-wireframes/Desktop Blog Page EaRRRth.png
  docs/wireframes/desktop-wireframes/Desktop Contribution Page EaRRRth.png
  docs/wireframes/desktop-wireframes/Desktop Landing Page EaRRRth.png
  docs/wireframes/desktop-wireframes/Desktop Profile Page EaRRRth.png
  docs/wireframes/mobile-wireframes/Mobile Blog Page EaRRRth.png
  docs/wireframes/mobile-wireframes/Mobile Contribution Page EaRRRth.png
  docs/wireframes/mobile-wireframes/Mobile Landing Page EaRRRth.png
  docs/wireframes/mobile-wireframes/Mobile Profile Page EaRRRth.png
  docs/wireframes/tablet-wireframes/Tablet Blog Page EaRRRth.png
  docs/wireframes/tablet-wireframes/Tablet Contribution Page EaRRRth.png
  docs/wireframes/tablet-wireframes/Tablet Landing Page EaRRRth.png
  docs/wireframes/tablet-wireframes/Tablet Profile Page EaRRRth.png
  home/templates/home/index.html
  profiles/migrations/0001_initial.py
  requirements.txt
  static/css/style.css
  templates/base.html
  wireframes/desktop-wireframes
Labels: documentation

#64 styled stats grid on home page, add custom error templates
  home/templates/home/index.html
  static/css/style.css
  templates/404.html
  templates/500.html
  templates/base.html
Labels: must have

#65 added bootstrap toasts + custom messages + lvls + msg icons
  contributions/views.py
  media/icons/icons8_eco.png
  media/icons/icons8_error.png
  media/icons/icons8_info.png
  media/icons/icons8_recycle.png
  media/icons/icons8_reduce.png
  media/icons/icons8_reuse.png
  media/icons/icons8_success.png
  media/images/icons8_recycle.png
  media/images/icons8_reuse.png
  templates/base.html
  templates/includes/toasts/toast_error.html
  templates/includes/toasts/toast_info.html
  templates/includes/toasts/toast_recycle.html
  templates/includes/toasts/toast_reduce.html
  templates/includes/toasts/toast_reuse.html
  templates/includes/toasts/toast_success.html
  templates/includes/toasts/toast_warning.html
Labels: must have

#67 New Additions to the README file
  README.md
  docs/color-palette/EaRRRth-Cooler-Palette.png
Labels: documentation

#68 Joel guttering issue cross app
  contributions/templates/contributions/contributions.html
  home/templates/home/index.html
  static/css/style.css
  templates/account/login.html
  templates/account/logout.html
  templates/account/signup.html
  templates/base.html
Labels: must have

#71 John t add user avatar upload
  contributions/forms.py
  contributions/migrations/0001_initial.py
  earrrth/settings.py
  profiles/forms.py
  profiles/migrations/0001_initial.py
  profiles/migrations/0002_profileimage.py
  profiles/migrations/0003_alter_profileimage_owner.py
  profiles/migrations/0004_auto_20220423_2335.py
  profiles/migrations/0005_alter_userprofile_image.py
  profiles/migrations/0006_alter_userprofile_image.py
  profiles/models.py
  profiles/templates/profiles/profile.html
  profiles/views.py
  reset.py
Labels: could have

#72 Noms profile branch
  earrrth/settings.py
  profiles/templates/profiles/profile.html
  profiles/views.py
  static/css/style.css
Labels: must have

#74 John t add messages to views
  contributions/views.py
  media/icons/icons8_ecosystem.png
  media/images/icons8_reduce.png
  profiles/migrations/0002_alter_userprofile_image.py
  profiles/migrations/0003_alter_userprofile_image.py
  profiles/models.py
  profiles/templates/profiles/profile.html
  profiles/views.py
  static/css/style.css
  static/images/account-hero-optimised.jpg
  static/images/contributions-hero-optimised.jpg
  static/images/earth_solid.png
  static/images/home-hero-optimised.jpg
  static/images/icons/icons8_eco.png
  static/images/icons/icons8_ecosystem.png
  static/images/icons/icons8_error.png
  static/images/icons/icons8_info.png
  static/images/icons/icons8_recycle.png
  static/images/icons/icons8_reduce.png
  static/images/icons/icons8_reuse.png
  static/images/icons/icons8_success.png
  static/images/icons8_recycle.png
  static/images/icons8_reduce.png
  static/images/icons8_reuse.png
Labels: must have

#76 Footer with Privacy Statement model button
  static/css/style.css
  templates/base.html
Labels: must have

#78 Details in commit history
  README.md
  contributions/templates/contributions/contributions.html
  contributions/views.py
  earrrth/settings.py
  earrrth/urls.py
  home/templates/home/index.html
  media/images/account-hero-optimised.webp
  media/images/contributions-hero-optimised.webp
  media/images/home-hero-optimised.webp
  profiles/templates/profiles/profile.html
  profiles/views.py
  static/css/style.css
  static/images/account-hero-optimised.jpg
  static/images/account-hero-optimised.webp
  static/images/contributions-hero-optimised.jpg
  static/images/contributions-hero-optimised.webp
  static/images/home-hero-optimised.jpg
  static/images/home-hero-optimised.webp
  templates/account/login.html
  templates/account/logout.html
  templates/account/signup.html
  templates/base.html
  templates/includes/toasts/toast_error.html
  templates/includes/toasts/toast_info.html
  templates/includes/toasts/toast_recycle.html
  templates/includes/toasts/toast_reduce.html
  templates/includes/toasts/toast_reuse.html
  templates/includes/toasts/toast_success.html
  templates/includes/toasts/toast_warning.html
Labels: must have

#79 Added responsive styling to profile page
  profiles/templates/profiles/profile.html
  static/css/style.css
Labels: enhancement

#81 MVP Deployment to Heroku
  contributions/templates/contributions/contributions.html
  contributions/views.py
  earrrth/settings.py
  static/css/style.css
  static/favicon/android-chrome-192x192.png
  static/favicon/android-chrome-512x512.png
  static/favicon/apple-touch-icon.png
  static/favicon/favicon-16x16.png
  static/favicon/favicon-32x32.png
  static/favicon/favicon.ico
  static/favicon/site.webmanifest
  static/images/earrrth_image.webp
  templates/account/signup.html
  templates/base.html
  templates/includes/favicon.html
  templates/includes/policy/privacy_policy.html
Labels: must have

#82 fixed styling for contributions page, profile pageand base template g…
  contributions/templates/contributions/contributions.html
  profiles/templates/profiles/profile.html
  templates/base.html
Labels: must have

#83 README Updates (Tests, Deployment, etc)
  README.md
  docs/data-schema/data_schema_plan.png
Labels: documentation

#85 added live link to readme
  README.md
Labels: could have
